# This file is automatically generated
###################
# List of include directories for exported targets

set(stereoVision_INCLUDE_DIRS /usr/local/robot/iCub/contrib/src/stereoVision/src/lib/include CACHE STRING "include dir for stereoVision")
include("/usr/local/robot/iCub/contrib/src/stereoVision/src/lib/stereoVision-export-build.cmake")
