SET(PM_PROJECT_NAME ForceClosureCalculator)
SET(PM_PROJECT_TYPE Executable)
SET(PM_PROJECT_DEPS MathLib)
SET(PM_EXTERNAL_INCDIR  ./lib/include)
SET(PM_EXTERNAL_LIBS    qhull)
SET(PM_EXTERNAL_LIBDIR  ./lib)

