obstacle_range: 2.5
raytrace_range: 3.0
robot_radius: 0.38
inflation_radius: 0.80
observation_sources: scan
scan: {sensor_frame: /base_laser, data_type: LaserScan, topic: /ikart_ros_bridge/laser_out, marking: true, clearing: true}
