set(PMP_HAS_GSL_LIB FALSE)
if( NOT EXISTS $ENV{GSL_DIR} )
	MESSAGE ( FATAL_ERROR "no GSL ENVIRONMENT VARIABLE found")

else( NOT EXISTS $ENV{GSL_DIR} )
	set(PMP_HAS_GSL_LIB TRUE)
	set (GSL_DIR "$ENV{GSL_DIR}" CACHE PATH "GSL_DIR path")
	message (STATUS "found GSL: $ENV{GSL_DIR}")

endif( NOT EXISTS $ENV{GSL_DIR} )

if(PMP_HAS_GSL_LIB)

# find GSL libraries
	set(GSL_LIB_PATH "$ENV{GSL_DIR}/lib" CACHE PATH "GSL_LIBRARIES path")
	if (NOT IS_DIRECTORY ${GSL_LIB_PATH})
		message ( FATAL ERROR "SPECIFY GSL libraries PATH")
	endif (NOT IS_DIRECTORY ${GSL_LIB_PATH})

	file (GLOB GSL_LIBRARIES ${GSL_LIB_PATH}/*.lib)
	message (STATUS "found GSL libraries: ${GSL_LIBRARIES}")

# find GSL headers
	set (GSL_INCLUDE_DIRS "$ENV{GSL_DIR}/include" CACHE PATH "GSL_INCLUDE_DIRS path")
	if (NOT IS_DIRECTORY ${GSL_INCLUDE_DIRS})
		message ( FATAL ERROR "SPECIFY GSL headers PATH")
	endif (NOT IS_DIRECTORY ${GSL_INCLUDE_DIRS})

	set( EXTERNAL_LIBRARIES ${GSL_LIBRARIES} )
	set( EXTERNAL_INCLUDES  ${GSL_INCLUDE_DIRS} )

endif(PMP_HAS_GSL_LIB)