# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/research/code/iCub/contrib/src/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/research/code/iCub/contrib/src/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/research/code/iCub/contrib/src/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/research/code/iCub/contrib/src/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/research/code/iCub/contrib/src/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/research/code/iCub/contrib/src/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/research/code/iCub/contrib/src/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/research/code/iCub/contrib/src/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/iCub/contrib/src/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/iCub/contrib/src/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/iCub/contrib/src/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/iCub/contrib/src/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/iCub/contrib/src/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/iCub/contrib/src/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/iCub/contrib/src/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/iCub/contrib/src/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/iCub/contrib/src/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/iCub/contrib/src/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/iCub/contrib/src/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/iCub/contrib/src/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/iCub/contrib/src/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/research/code/iCub/contrib/src/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/research/code/iCub/contrib/src/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/iCub/contrib/src/controlBasis/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/iCub/contrib/src/controlBasis/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/iCub/contrib/src/controlBasis/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/iCub/contrib/src/controlBasis/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/iCub/contrib/src/controlBasis/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/iCub/contrib/src/controlBasis/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/iCub/contrib/src/controlBasis/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/iCub/contrib/src/controlBasis/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/iCub/contrib/src/controlBasis/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/iCub/contrib/src/controlBasis/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/iCub/contrib/src/controlBasis/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/iCub/contrib/src/controlBasis/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/iCub/contrib/src/controlBasis/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/iCub/contrib/src/controlBasis/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/iCub/contrib/src/controlBasis/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/iCub/contrib/src/controlBasis/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;yarpcar;YARP_name;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/iCub/contrib/src/controlBasis/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;yarpcar;YARP_name;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/iCub/contrib/src/controlBasis/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;yarpcar;YARP_name;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/iCub/contrib/src/controlBasis/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;yarpcar;YARP_name;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/iCub/contrib/src/controlBasis/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;yarpcar;YARP_name;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/iCub/contrib/src/controlBasis/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;yarpcar;YARP_name;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/iCub/contrib/src/controlBasis/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;yarpcar;YARP_name;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/iCub/contrib/src/controlBasis/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;yarpcar;YARP_name;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/iCub/contrib/src/controlBasis/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;yarpcar;YARP_name;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/iCub/contrib/src/controlBasis/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 0

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;YARP_name;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/usr/local/src/robot/iCub/contrib/src/controlBasis/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 0

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;YARP_name;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/usr/local/src/robot/iCub/contrib/src/controlBasis/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;yarpcar;YARP_name;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/iCub/contrib/src/controlBasis/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;yarpcar;YARP_name;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/iCub/contrib/src/controlBasis/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 0

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;YARP_name;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/usr/local/src/robot/iCub/contrib/src/controlBasis/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;yarpcar;YARP_name;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/iCub/contrib/src/controlBasis/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;yarpcar;YARP_name;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/iCub/contrib/src/controlBasis/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;yarpcar;YARP_name;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/iCub/contrib/src/controlBasis/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;yarpcar;YARP_name;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/iCub/contrib/src/controlBasis/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;yarpcar;YARP_name;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/iCub/contrib/src/controlBasis/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;yarpcar;YARP_name;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/iCub/contrib/src/controlBasis/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;yarpcar;YARP_name;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/iCub/contrib/src/controlBasis/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;yarpcar;YARP_name;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/research/code/iCub/contrib/src/controlBasis/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;yarpcar;YARP_name;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/research/code/iCub/contrib/src/controlBasis/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;yarpcar;YARP_name;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/research/code/iCub/contrib/src/controlBasis/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;yarpcar;YARP_name;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/research/code/iCub/contrib/src/controlBasis/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;yarpcar;YARP_name;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/research/code/iCub/contrib/src/controlBasis/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;yarpcar;YARP_name;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/research/code/iCub/contrib/src/controlBasis/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;yarpcar;YARP_name;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/research/code/iCub/contrib/src/controlBasis/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;yarpcar;YARP_name;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/research/code/iCub/contrib/src/controlBasis/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;yarpcar;YARP_name;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/research/code/iCub/contrib/src/controlBasis/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;yarpcar;YARP_name;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/iCub/contrib/src/controlBasis/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;yarpcar;YARP_name;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/iCub/contrib/src/controlBasis/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 4

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;yarpmod;yarpcar;YARP_name;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/home/hart/iCub/contrib/src/controlBasis/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 0

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;YARP_name;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/usr/local/src/robot/iCub/contrib/src/controlBasis/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.6-patch 0

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target controlBasis
ADD_LIBRARY(controlBasis STATIC IMPORTED)

# Import target "controlBasis" for configuration ""
SET_PROPERTY(TARGET controlBasis APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(controlBasis PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "YARP_OS;YARP_sig;YARP_math;YARP_dev;YARP_name;YARP_init;iKin;rl;learningMachine"
  IMPORTED_LOCATION_NOCONFIG "/usr/local/src/robot/iCub/contrib/src/controlBasis/libraries/controlBasis/libcontrolBasis.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
